# Generated by Django 4.2.29 on 2026-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_profile_business_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('shop_admin', 'Shop Admin')], default='customer', max_length=10),
        ),
    ]
