# Generated by Django 4.2.29 on 2026-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_savedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Qwerty Junior', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(default='CR0 2RR', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='London', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='54 Bensham Lane', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default='50', max_digits=10),
            preserve_default=False,
        ),
    ]
