# Generated by Django 4.2.29 on 2026-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='grid_intensity',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='material_sustainability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('recycled_polyester', 'Recycled Polyester'), ('virgin_polyester', 'Virgin Polyester'), ('cotton', 'Cotton')], default='cotton', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='transport_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='transport_mode',
            field=models.CharField(choices=[('air', 'Air'), ('truck', 'Truck'), ('sea', 'Sea')], default='truck', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
