# Generated by Django 4.2.29 on 2026-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_carbon_footprint_product_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_co2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='baseline_co2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='co2_saved',
            field=models.FloatField(default=0.0),
        ),
    ]
