# Generated by Django 4.2.29 on 2026-04-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_actual_co2_product_baseline_co2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='baseline_co2',
            new_name='co2_baseline',
        ),
    ]
