# Generated by Django 4.2.29 on 2026-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_baseline_co2_product_co2_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transport_distance',
            field=models.FloatField(default=2.0),
        ),
    ]
